# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sgy8-8fbjYbY5T4LmuIfZFrG2aKcQPRN
"""

import re

example = "I love spending time at https://www.xy123z.com/
url_pattern = r'https?://[^\s"]+'


urls = re.findall(url_pattern, example)

print(urls)

import re

example = "My email id is xyz111@gmail.com"

pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'


emails = re.findall(pattern, example)

print("Email found:", emails)

import re

text = "#sourabh is trending now in the world."
hashtags = re.findall(r'#\w+', text)

print(hashtags)

import re

# Example sentence
text = "Hey @john, have you seen the post by @bhati and @sourabh?"

# Find all mentions starting with @
mentions = re.findall(r'@\w+', text)

print("Mentions found:", mentions)

import re

example = "8853147 sq. km of area washed away in floods"
numbers = re.findall(r'\d+', example)

print(numbers)

import string

example = "Corona virus killed #24506 people. #Corona is un(tolerable)"
punctuations = [char for char in example if char in string.punctuation]

print("Punctuations found:", punctuations)

import re

def validate_pan(pan):
    pattern = r'^[A-Z]{6}[0-9]{4}[A-Z]$'
    return bool(re.match(pattern, pan))

# Examples
pan1 = "ABCED3193P"
pan2 = "lEcGD012eg"

import re

example = "heyyy this is a verrrry loong texttt"

# Replace repeated characters (2 or more) with a single instance
cleaned = re.sub(r'(.)\1+', r'\1', example)

print("Cleaned sentence:", cleaned)